"""phase7c_hemis_sync_log

Revision ID: 10a192829638
Revises: 60ebb5a8b0b5
Create Date: 2026-05-18 08:44:05.328412

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10a192829638'
down_revision: str | None = '60ebb5a8b0b5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hemis_sync_log',
    sa.Column('sync_type', sa.String(length=40), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hemis_sync_log'))
    )
    op.create_index(op.f('ix_hemis_sync_log_status'), 'hemis_sync_log', ['status'], unique=False)
    op.create_index(op.f('ix_hemis_sync_log_sync_type'), 'hemis_sync_log', ['sync_type'], unique=False)
    op.create_index(op.f('ix_hemis_sync_log_target_id'), 'hemis_sync_log', ['target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hemis_sync_log_target_id'), table_name='hemis_sync_log')
    op.drop_index(op.f('ix_hemis_sync_log_sync_type'), table_name='hemis_sync_log')
    op.drop_index(op.f('ix_hemis_sync_log_status'), table_name='hemis_sync_log')
    op.drop_table('hemis_sync_log')
    # ### end Alembic commands ###
