"""phase4b_rubrics_grading

Revision ID: 1b03eda4d15f
Revises: 0c0689e18e37
Create Date: 2026-05-09 18:25:34.092841

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b03eda4d15f'
down_revision: str | None = '0c0689e18e37'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rubrics',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_points', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_rubrics_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_rubrics_organization_id_organizations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rubrics'))
    )
    op.create_index(op.f('ix_rubrics_created_by'), 'rubrics', ['created_by'], unique=False)
    op.create_index(op.f('ix_rubrics_organization_id'), 'rubrics', ['organization_id'], unique=False)
    op.add_column('assignments', sa.Column('rubric_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_assignments_rubric_id'), 'assignments', ['rubric_id'], unique=False)
    op.create_foreign_key(op.f('fk_assignments_rubric_id_rubrics'), 'assignments', 'rubrics', ['rubric_id'], ['id'], ondelete='SET NULL')
    op.add_column('submissions', sa.Column('grade_letter', sa.String(length=5), nullable=True))
    # Mavjud qatorlar uchun bo'sh JSON default — keyin model standart qiymatlarni ishlatadi
    op.add_column(
        'submissions',
        sa.Column(
            'rubric_scores',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )
    op.add_column(
        'submissions',
        sa.Column(
            'annotations',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'annotations')
    op.drop_column('submissions', 'rubric_scores')
    op.drop_column('submissions', 'grade_letter')
    op.drop_constraint(op.f('fk_assignments_rubric_id_rubrics'), 'assignments', type_='foreignkey')
    op.drop_index(op.f('ix_assignments_rubric_id'), table_name='assignments')
    op.drop_column('assignments', 'rubric_id')
    op.drop_index(op.f('ix_rubrics_organization_id'), table_name='rubrics')
    op.drop_index(op.f('ix_rubrics_created_by'), table_name='rubrics')
    op.drop_table('rubrics')
    # ### end Alembic commands ###
