"""phase9d_code_test_cases

Revision ID: 240f191605f3
Revises: 28bacdd504a3
Create Date: 2026-05-19 08:35:59.656920

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '240f191605f3'
down_revision: str | None = '28bacdd504a3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_code_test_cases',
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('stdin', sa.Text(), nullable=False),
    sa.Column('expected_stdout', sa.Text(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['exam_questions.id'], name=op.f('fk_exam_code_test_cases_question_id_exam_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_code_test_cases'))
    )
    op.create_index(op.f('ix_exam_code_test_cases_question_id'), 'exam_code_test_cases', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exam_code_test_cases_question_id'), table_name='exam_code_test_cases')
    op.drop_table('exam_code_test_cases')
    # ### end Alembic commands ###
