"""phase9c_live_captions

Revision ID: 28bacdd504a3
Revises: f2c66ddd136f
Create Date: 2026-05-18 15:57:05.573425

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '28bacdd504a3'
down_revision: str | None = 'f2c66ddd136f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_captions',
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('speaker_user_id', sa.BigInteger(), nullable=True),
    sa.Column('start_ms', sa.BigInteger(), nullable=False),
    sa.Column('end_ms', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('lang', sa.String(length=10), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['live_sessions.id'], name=op.f('fk_live_captions_session_id_live_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaker_user_id'], ['users.id'], name=op.f('fk_live_captions_speaker_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_live_captions'))
    )
    op.create_index(op.f('ix_live_captions_session_id'), 'live_captions', ['session_id'], unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_live_captions_session_id'), table_name='live_captions')
    op.drop_table('live_captions')
    # ### end Alembic commands ###
