"""phase4e_plagiarism_peer_appeals

Revision ID: 438a7aa08cc1
Revises: 1b03eda4d15f
Create Date: 2026-05-10 09:04:43.688647

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '438a7aa08cc1'
down_revision: str | None = '1b03eda4d15f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade_appeals',
    sa.Column('submission_id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('new_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.BigInteger(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_grade_appeals_reviewed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_grade_appeals_student_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], name=op.f('fk_grade_appeals_submission_id_submissions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grade_appeals'))
    )
    op.create_index(op.f('ix_grade_appeals_status'), 'grade_appeals', ['status'], unique=False)
    op.create_index(op.f('ix_grade_appeals_student_id'), 'grade_appeals', ['student_id'], unique=False)
    op.create_index(op.f('ix_grade_appeals_submission_id'), 'grade_appeals', ['submission_id'], unique=False)
    op.create_table('peer_reviews',
    sa.Column('submission_id', sa.BigInteger(), nullable=False),
    sa.Column('reviewer_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('rubric_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_peer_reviews_reviewer_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], name=op.f('fk_peer_reviews_submission_id_submissions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_peer_reviews')),
    sa.UniqueConstraint('submission_id', 'reviewer_id', name='uq_peer_review_sub_reviewer')
    )
    op.create_index(op.f('ix_peer_reviews_reviewer_id'), 'peer_reviews', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_peer_reviews_submission_id'), 'peer_reviews', ['submission_id'], unique=False)
    # Mavjud qatorlar uchun standart qiymatlar (model'dagi default'lar bilan teng)
    op.add_column('assignments', sa.Column('plagiarism_check_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('assignments', sa.Column('plagiarism_threshold', sa.Numeric(precision=5, scale=2), nullable=False, server_default=sa.text('30')))
    op.add_column('assignments', sa.Column('peer_review_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('assignments', sa.Column('peer_reviews_per_submission', sa.Integer(), nullable=False, server_default=sa.text('3')))
    op.add_column('submissions', sa.Column('plagiarism_score', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('submissions', sa.Column('plagiarism_report_url', sa.Text(), nullable=True))
    op.add_column('submissions', sa.Column('plagiarism_flagged', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('submissions', sa.Column('plagiarism_checked_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('submissions', 'rubric_scores',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('submissions', 'annotations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submissions', 'annotations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=False)
    op.alter_column('submissions', 'rubric_scores',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.drop_column('submissions', 'plagiarism_checked_at')
    op.drop_column('submissions', 'plagiarism_flagged')
    op.drop_column('submissions', 'plagiarism_report_url')
    op.drop_column('submissions', 'plagiarism_score')
    op.drop_column('assignments', 'peer_reviews_per_submission')
    op.drop_column('assignments', 'peer_review_enabled')
    op.drop_column('assignments', 'plagiarism_threshold')
    op.drop_column('assignments', 'plagiarism_check_enabled')
    op.drop_index(op.f('ix_peer_reviews_submission_id'), table_name='peer_reviews')
    op.drop_index(op.f('ix_peer_reviews_reviewer_id'), table_name='peer_reviews')
    op.drop_table('peer_reviews')
    op.drop_index(op.f('ix_grade_appeals_submission_id'), table_name='grade_appeals')
    op.drop_index(op.f('ix_grade_appeals_student_id'), table_name='grade_appeals')
    op.drop_index(op.f('ix_grade_appeals_status'), table_name='grade_appeals')
    op.drop_table('grade_appeals')
    # ### end Alembic commands ###
