"""phase9e_plagiarism_fields

Revision ID: 447f43ea7080
Revises: 240f191605f3
Create Date: 2026-05-19 10:06:56.658772

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '447f43ea7080'
down_revision: str | None = '240f191605f3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_answers', sa.Column('plagiarism_score', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('exam_answers', sa.Column('plagiarism_match_answer_id', sa.BigInteger(), nullable=True))
    op.add_column('exam_answers', sa.Column('plagiarism_checked_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(op.f('fk_exam_answers_plagiarism_match_answer_id_exam_answers'), 'exam_answers', 'exam_answers', ['plagiarism_match_answer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_exam_answers_plagiarism_match_answer_id_exam_answers'), 'exam_answers', type_='foreignkey')
    op.drop_column('exam_answers', 'plagiarism_checked_at')
    op.drop_column('exam_answers', 'plagiarism_match_answer_id')
    op.drop_column('exam_answers', 'plagiarism_score')
    # ### end Alembic commands ###
