"""phase1e_user_hemis_id

Revision ID: 4ee56d490e18
Revises: 22ee19edf9af
Create Date: 2026-05-07 17:26:29.893233

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '4ee56d490e18'
down_revision: str | None = '22ee19edf9af'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hemis_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_users_hemis_id'), 'users', ['hemis_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_hemis_id'), table_name='users')
    op.drop_column('users', 'hemis_id')
    # ### end Alembic commands ###
