"""phase2a_academic_structure

Revision ID: 5894778d82d7
Revises: 4ee56d490e18
Create Date: 2026-05-07 18:04:31.056773

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5894778d82d7'
down_revision: str | None = '4ee56d490e18'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_calendars',
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('semesters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('holidays', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_academic_calendars_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_academic_calendars')),
    sa.UniqueConstraint('organization_id', 'academic_year', name='uq_calendar_org_year')
    )
    op.create_index(op.f('ix_academic_calendars_organization_id'), 'academic_calendars', ['organization_id'], unique=False)
    op.create_table('faculties',
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('dean_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dean_id'], ['users.id'], name=op.f('fk_faculties_dean_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_faculties_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_faculties')),
    sa.UniqueConstraint('organization_id', 'code', name='uq_faculty_org_code')
    )
    op.create_index(op.f('ix_faculties_organization_id'), 'faculties', ['organization_id'], unique=False)
    op.create_table('departments',
    sa.Column('faculty_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('head_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], name=op.f('fk_departments_faculty_id_faculties'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['head_id'], ['users.id'], name=op.f('fk_departments_head_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('faculty_id', 'code', name='uq_department_faculty_code')
    )
    op.create_index(op.f('ix_departments_faculty_id'), 'departments', ['faculty_id'], unique=False)
    op.create_table('specialties',
    sa.Column('department_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('duration_years', sa.Integer(), nullable=False),
    sa.Column('education_form', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('distance_enabled', sa.Boolean(), nullable=False),
    sa.Column('annual_quota', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_specialties_department_id_departments'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_specialties'))
    )
    op.create_index(op.f('ix_specialties_code'), 'specialties', ['code'], unique=True)
    op.create_index(op.f('ix_specialties_department_id'), 'specialties', ['department_id'], unique=False)
    op.create_index(op.f('ix_specialties_level'), 'specialties', ['level'], unique=False)
    op.create_table('subjects',
    sa.Column('department_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('lecture_hours', sa.Integer(), nullable=False),
    sa.Column('practice_hours', sa.Integer(), nullable=False),
    sa.Column('seminar_hours', sa.Integer(), nullable=False),
    sa.Column('self_study_hours', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_subjects_department_id_departments'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects'))
    )
    op.create_index(op.f('ix_subjects_code'), 'subjects', ['code'], unique=True)
    op.create_index(op.f('ix_subjects_department_id'), 'subjects', ['department_id'], unique=False)
    op.create_table('curricula',
    sa.Column('specialty_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('based_on', sa.String(length=50), nullable=True),
    sa.Column('standard_code', sa.String(length=50), nullable=True),
    sa.Column('total_credits', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.BigInteger(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_curricula_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], name=op.f('fk_curricula_specialty_id_specialties'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_curricula'))
    )
    op.create_index(op.f('ix_curricula_specialty_id'), 'curricula', ['specialty_id'], unique=False)
    op.create_table('subject_prerequisites',
    sa.Column('subject_id', sa.BigInteger(), nullable=False),
    sa.Column('prerequisite_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['subjects.id'], name=op.f('fk_subject_prerequisites_prerequisite_id_subjects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_subject_prerequisites_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subject_id', 'prerequisite_id', name=op.f('pk_subject_prerequisites'))
    )
    op.create_table('curriculum_subjects',
    sa.Column('curriculum_id', sa.BigInteger(), nullable=False),
    sa.Column('subject_id', sa.BigInteger(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curricula.id'], name=op.f('fk_curriculum_subjects_curriculum_id_curricula'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_curriculum_subjects_subject_id_subjects'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_curriculum_subjects')),
    sa.UniqueConstraint('curriculum_id', 'subject_id', 'semester', name='uq_curr_subject_semester')
    )
    op.create_index(op.f('ix_curriculum_subjects_curriculum_id'), 'curriculum_subjects', ['curriculum_id'], unique=False)
    op.add_column('organizations', sa.Column('type', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('license_number', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('rector_id', sa.BigInteger(), nullable=True))
    op.add_column('organizations', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('organizations', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('domain', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('logo_url', sa.Text(), nullable=True))
    op.add_column('organizations', sa.Column('branding', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('organizations', sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.alter_column('organizations', 'code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('organizations', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=300),
               existing_nullable=False)
    op.create_unique_constraint(op.f('uq_organizations_domain'), 'organizations', ['domain'])
    op.create_foreign_key(op.f('fk_organizations_rector_id_users'), 'organizations', 'users', ['rector_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_organizations_rector_id_users'), 'organizations', type_='foreignkey')
    op.drop_constraint(op.f('uq_organizations_domain'), 'organizations', type_='unique')
    op.alter_column('organizations', 'name',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('organizations', 'code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('organizations', 'settings')
    op.drop_column('organizations', 'branding')
    op.drop_column('organizations', 'logo_url')
    op.drop_column('organizations', 'domain')
    op.drop_column('organizations', 'website')
    op.drop_column('organizations', 'email')
    op.drop_column('organizations', 'phone')
    op.drop_column('organizations', 'address')
    op.drop_column('organizations', 'rector_id')
    op.drop_column('organizations', 'license_number')
    op.drop_column('organizations', 'type')
    op.drop_index(op.f('ix_curriculum_subjects_curriculum_id'), table_name='curriculum_subjects')
    op.drop_table('curriculum_subjects')
    op.drop_table('subject_prerequisites')
    op.drop_index(op.f('ix_curricula_specialty_id'), table_name='curricula')
    op.drop_table('curricula')
    op.drop_index(op.f('ix_subjects_department_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_code'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_specialties_level'), table_name='specialties')
    op.drop_index(op.f('ix_specialties_department_id'), table_name='specialties')
    op.drop_index(op.f('ix_specialties_code'), table_name='specialties')
    op.drop_table('specialties')
    op.drop_index(op.f('ix_departments_faculty_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_faculties_organization_id'), table_name='faculties')
    op.drop_table('faculties')
    op.drop_index(op.f('ix_academic_calendars_organization_id'), table_name='academic_calendars')
    op.drop_table('academic_calendars')
    # ### end Alembic commands ###
