"""phase7a_live_recordings

Revision ID: 60ebb5a8b0b5
Revises: 6fae9c34345d
Create Date: 2026-05-17 15:31:13.923706

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '60ebb5a8b0b5'
down_revision: str | None = '6fae9c34345d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_recordings',
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('recorded_by', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=60), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], name=op.f('fk_live_recordings_recorded_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['live_sessions.id'], name=op.f('fk_live_recordings_session_id_live_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_live_recordings'))
    )
    op.create_index(op.f('ix_live_recordings_session_id'), 'live_recordings', ['session_id'], unique=False)
    op.create_index(op.f('ix_live_recordings_status'), 'live_recordings', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_live_recordings_status'), table_name='live_recordings')
    op.drop_index(op.f('ix_live_recordings_session_id'), table_name='live_recordings')
    op.drop_table('live_recordings')
    # ### end Alembic commands ###
