"""phase6f_proctoring

Revision ID: 6fae9c34345d
Revises: faddaee20422
Create Date: 2026-05-16 08:19:04.614335

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6fae9c34345d'
down_revision: str | None = 'faddaee20422'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_id_reference_photos',
    sa.Column('attempt_id', sa.BigInteger(), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['exam_attempts.id'], name=op.f('fk_exam_id_reference_photos_attempt_id_exam_attempts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_id_reference_photos'))
    )
    op.create_index(op.f('ix_exam_id_reference_photos_attempt_id'), 'exam_id_reference_photos', ['attempt_id'], unique=True)
    op.create_table('exam_proctoring_events',
    sa.Column('attempt_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['exam_attempts.id'], name=op.f('fk_exam_proctoring_events_attempt_id_exam_attempts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_proctoring_events'))
    )
    op.create_index(op.f('ix_exam_proctoring_events_attempt_id'), 'exam_proctoring_events', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_exam_proctoring_events_event_type'), 'exam_proctoring_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_exam_proctoring_events_occurred_at'), 'exam_proctoring_events', ['occurred_at'], unique=False)
    op.create_table('exam_proctoring_snapshots',
    sa.Column('attempt_id', sa.BigInteger(), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('face_count', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('bytes_size', sa.BigInteger(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['exam_attempts.id'], name=op.f('fk_exam_proctoring_snapshots_attempt_id_exam_attempts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_proctoring_snapshots'))
    )
    op.create_index(op.f('ix_exam_proctoring_snapshots_attempt_id'), 'exam_proctoring_snapshots', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_exam_proctoring_snapshots_captured_at'), 'exam_proctoring_snapshots', ['captured_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exam_proctoring_snapshots_captured_at'), table_name='exam_proctoring_snapshots')
    op.drop_index(op.f('ix_exam_proctoring_snapshots_attempt_id'), table_name='exam_proctoring_snapshots')
    op.drop_table('exam_proctoring_snapshots')
    op.drop_index(op.f('ix_exam_proctoring_events_occurred_at'), table_name='exam_proctoring_events')
    op.drop_index(op.f('ix_exam_proctoring_events_event_type'), table_name='exam_proctoring_events')
    op.drop_index(op.f('ix_exam_proctoring_events_attempt_id'), table_name='exam_proctoring_events')
    op.drop_table('exam_proctoring_events')
    op.drop_index(op.f('ix_exam_id_reference_photos_attempt_id'), table_name='exam_id_reference_photos')
    op.drop_table('exam_id_reference_photos')
    # ### end Alembic commands ###
