"""phase9f_smart_score

Revision ID: 7ad275b7020e
Revises: 447f43ea7080
Create Date: 2026-05-19 10:23:09.787008

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ad275b7020e'
down_revision: str | None = '447f43ea7080'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_attempts', sa.Column('smart_score', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('exam_attempts', sa.Column('smart_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_attempts', 'smart_flags')
    op.drop_column('exam_attempts', 'smart_score')
    # ### end Alembic commands ###
