"""phase5a_live_sessions

Revision ID: d79a0f58f314
Revises: 438a7aa08cc1
Create Date: 2026-05-10 11:49:54.952980

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd79a0f58f314'
down_revision: str | None = '438a7aa08cc1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_sessions',
    sa.Column('organization_id', sa.BigInteger(), nullable=True),
    sa.Column('course_id', sa.BigInteger(), nullable=True),
    sa.Column('lesson_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_meeting_id', sa.String(length=200), nullable=True),
    sa.Column('provider_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('host_user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_recording_enabled', sa.Boolean(), nullable=False),
    sa.Column('recording_url', sa.Text(), nullable=True),
    sa.Column('min_attendance_percent', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_live_sessions_course_id_courses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['host_user_id'], ['users.id'], name=op.f('fk_live_sessions_host_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_live_sessions_lesson_id_lessons'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_live_sessions_organization_id_organizations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_live_sessions'))
    )
    op.create_index(op.f('ix_live_sessions_course_id'), 'live_sessions', ['course_id'], unique=False)
    op.create_index(op.f('ix_live_sessions_host_user_id'), 'live_sessions', ['host_user_id'], unique=False)
    op.create_index(op.f('ix_live_sessions_lesson_id'), 'live_sessions', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_live_sessions_organization_id'), 'live_sessions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_live_sessions_scheduled_start'), 'live_sessions', ['scheduled_start'], unique=False)
    op.create_index(op.f('ix_live_sessions_status'), 'live_sessions', ['status'], unique=False)
    op.create_table('live_attendance',
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_minutes', sa.Integer(), nullable=False),
    sa.Column('is_counted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['live_sessions.id'], name=op.f('fk_live_attendance_session_id_live_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_live_attendance_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_live_attendance')),
    sa.UniqueConstraint('session_id', 'user_id', name='uq_live_attendance_session_user')
    )
    op.create_index(op.f('ix_live_attendance_session_id'), 'live_attendance', ['session_id'], unique=False)
    op.create_index(op.f('ix_live_attendance_user_id'), 'live_attendance', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_live_attendance_user_id'), table_name='live_attendance')
    op.drop_index(op.f('ix_live_attendance_session_id'), table_name='live_attendance')
    op.drop_table('live_attendance')
    op.drop_index(op.f('ix_live_sessions_status'), table_name='live_sessions')
    op.drop_index(op.f('ix_live_sessions_scheduled_start'), table_name='live_sessions')
    op.drop_index(op.f('ix_live_sessions_organization_id'), table_name='live_sessions')
    op.drop_index(op.f('ix_live_sessions_lesson_id'), table_name='live_sessions')
    op.drop_index(op.f('ix_live_sessions_host_user_id'), table_name='live_sessions')
    op.drop_index(op.f('ix_live_sessions_course_id'), table_name='live_sessions')
    op.drop_table('live_sessions')
    # ### end Alembic commands ###
