"""phase6b_attempts_answers

Revision ID: faddaee20422
Revises: 4239a5647010
Create Date: 2026-05-16 06:04:38.196478

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'faddaee20422'
down_revision: str | None = '4239a5647010'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_attempts',
    sa.Column('exam_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('auto_score', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('manual_score', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('total_score', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('max_score', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('question_order', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('option_order', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('proctoring_session_id', sa.BigInteger(), nullable=True),
    sa.Column('violation_score', sa.Integer(), nullable=False),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_exam_attempts_exam_id_exams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_exam_attempts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_attempts')),
    sa.UniqueConstraint('exam_id', 'user_id', 'attempt_number', name='uq_attempt_user_number')
    )
    op.create_index(op.f('ix_exam_attempts_exam_id'), 'exam_attempts', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_attempts_status'), 'exam_attempts', ['status'], unique=False)
    op.create_index(op.f('ix_exam_attempts_user_id'), 'exam_attempts', ['user_id'], unique=False)
    op.create_table('exam_answers',
    sa.Column('attempt_id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('selected_option_ids', postgresql.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('text_answer', sa.Text(), nullable=True),
    sa.Column('code_answer', sa.Text(), nullable=True),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('auto_correct', sa.Boolean(), nullable=True),
    sa.Column('points_earned', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('points_max', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('graded_by', sa.BigInteger(), nullable=True),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grader_comment', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['exam_attempts.id'], name=op.f('fk_exam_answers_attempt_id_exam_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['graded_by'], ['users.id'], name=op.f('fk_exam_answers_graded_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['exam_questions.id'], name=op.f('fk_exam_answers_question_id_exam_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_answers')),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_answer_attempt_question')
    )
    op.create_index(op.f('ix_exam_answers_attempt_id'), 'exam_answers', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_exam_answers_question_id'), 'exam_answers', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exam_answers_question_id'), table_name='exam_answers')
    op.drop_index(op.f('ix_exam_answers_attempt_id'), table_name='exam_answers')
    op.drop_table('exam_answers')
    op.drop_index(op.f('ix_exam_attempts_user_id'), table_name='exam_attempts')
    op.drop_index(op.f('ix_exam_attempts_status'), table_name='exam_attempts')
    op.drop_index(op.f('ix_exam_attempts_exam_id'), table_name='exam_attempts')
    op.drop_table('exam_attempts')
    # ### end Alembic commands ###
